version: "3.6"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.1
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefixStrip:/elastic/"
        - "traefik.port=9200"
      update_config:
        order: start-first
    environment:
      - cluster.name=VTMon
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - xpack.monitoring.collection.enabled=true
    volumes:
      - /opt/docker/stack.elastic/service.elasticsearch-1/data:/usr/share/elasticsearch/data
    #healthcheck:
    #  test: "curl -fsSL -o /dev/null 'http://localhost:9200'"
    #  interval: 10s
    #  timeout: 1s
    #  retries: 3
    networks:
      elastic-net:
        aliases:
         - elasticsearch
      traefik-net:


  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.1
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefix:/kibana"
        - "traefik.port=5601"
      update_config:
        order: start-first
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200/
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
      - node.name=kibana
    #healthcheck:
    #  test: "curl -fsSL -o /dev/null 'http://localhost:5601/kibana'"
    #  interval: 10s
    #  timeout: 1s
    #  retries: 3
    networks:
      - elastic-net
      - traefik-net
    depends_on:
      - elasticsearch

  cerebro:
    image:  yannart/cerebro:latest
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 0
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefix:/cerebro/"
        - "traefik.port=9000"
    configs:
      - source: Elastic_cerebro-cerebro.conf-20190514.1312
        target: /opt/cerebro/conf/application.conf
    networks:
      - elastic-net
      - traefik-net

configs:
  Elastic_cerebro-cerebro.conf-20190514.1312:
    external: true

networks:
  elastic-net:
    external: true
  traefik-net:
    external: true
