version: "3.6"

services:
  elasticsearch01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefixStrip:/elastic/"
        - "traefik.port=9200"
      update_config:
        order: stop-first
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    environment:
      - cluster.name=VTMon
      - node.name=elasticsearch01
      - discovery.seed_hosts=elasticsearch01
      - cluster.initial_master_nodes=elasticsearch01
      - xpack.monitoring.collection.enabled=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=true
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=false
    volumes:
      - /opt/docker/stack.elastic/service.elasticsearch01/data:/usr/share/elasticsearch/data
    healthcheck:
      test: "curl -fsSL -o /dev/null -u elastic:${ELASTIC_PASSWORD} 'http://localhost:9200'"
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s
    networks:
      elastic-net:
        aliases:
         - elasticsearch01
      traefik-net:


  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefix:/kibana"
        - "traefik.port=5601"
      update_config:
        order: start-first
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch01:9200/
      - SERVER_BASEPATH=/kibana
      - SERVER_REWRITEBASEPATH=true
      - NODE_NAME=kibana
      - XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=true
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD="${ELASTIC_PASSWORD}"
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_KIBANA_COLLECTION_ENABLED=true
      - XPACK_APM_UI_ENABLED=false
    healthcheck:
      test: "curl -fsSL -o /dev/null 'http://localhost:5601/kibana'"
      interval: 10s
      timeout: 2s
      retries: 3
      start_period: 60s
    networks:
      - elastic-net
      - traefik-net
    depends_on:
      - elasticsearch

  cerebro:
    image:  yannart/cerebro:latest
    deploy:
      update_config:
        order: start-first
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefix:/cerebro/"
        - "traefik.port=9000"
    configs:
      - source: Elastic_cerebro-cerebro.conf-20190621.1231
        target: /opt/cerebro/conf/application.conf
    networks:
      - elastic-net
      - traefik-net

configs:
  Elastic_cerebro-cerebro.conf-20190621.1231:
    external: true

networks:
  elastic-net:
    external: true
  traefik-net:
    external: true
