version: "3.6"

services:
  docker:
    image: docker.elastic.co/beats/filebeat:7.1.1
    command: filebeat -e -strict.perms=false
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: stop-first
   
    
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro 
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    networks:
      - elastic-net

networks:
  elastic-net:
    external: true