version: "3.6"

services:
  grafana:
    image: grafana/grafana:7.5.4
    volumes:
      - /opt/docker/Grafana/grafana/data:/var/lib/grafana
    networks:
      - graphhouse-net
    ports:
      - "80:3000"
    environment:
      - GF_INSTALL_PLUGINS=yesoreyeram-boomtable-panel,petrslavotinek-carpetplot-panel,vonage-status-panel,flant-statusmap-panel,grafana-piechart-panel
    deploy:
      mode: replicated
      replicas: 1

networks:
  graphhouse-net:
    external: true
