version: "3.6"

services:
  api:
    image: openmetric/carbonapi:0.11.0
    configs:
      - source: Graphite_api-api.yaml-20190517.0831
        target: /openmetric/conf/api.yaml
    healthcheck:
      test: "curl -fsSL -o /dev/null http://localhost:8080/lb_check"
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - graphite-net


  carbon:
    image: openmetric/go-carbon:v0.13.0
    configs:
      - source: Graphite_carbon-carbon.conf-20190517.0836
        target: /openmetric/conf/carbon.conf
      - source: Graphite_carbon-schemas.conf-20190517.0836
        target: /openmetric/conf/schemas.conf
    volumes:
      - /opt/docker/stack.graphite/service.carbon/whisper:/openmetric/data/whisper
    healthcheck:
      test: "curl -fsSL -o /dev/null 'http://localhost:8080/metrics/find/?query=*&format=json'"
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - graphite-net


  relay:
    image: openmetric/carbon-c-relay:v3.5
    command: carbon-c-relay -f /openmetric/conf/relay.conf -c -_:#@%$$|
    configs:
      - source: Graphite_relay_relay.conf-20190517.0847
        target: /openmetric/conf/relay.conf
#    volumes:
#      - /opt/docker/stk.graphite/svc.relay/relay.conf:/openmetric/conf/relay.conf:ro
    ports:
      - "2003:2003"
    depends_on:
      - carbon
    healthcheck:
      test: nc -zv localhost 2003
      interval: 10s
      timeout: 1s
      retries: 3
    networks:
      - graphite-net


configs:
  Graphite_api-api.yaml-20190517.0831:
    external: true
  Graphite_carbon-carbon.conf-20190517.0836:
    external: true
  Graphite_carbon-schemas.conf-20190517.0836:
    external: true
  Graphite_relay_relay.conf-20190517.0847:
    external: true


networks:
  graphite-net:
    external: true