version: "3.6"

services:
  api:
    image: gographite/carbonapi:v0.15.2
    deploy:
      mode: replicated
      replicas: 1
    #configs:
    #  - source: GraphHouse_api-api.yaml-20190530.1000
    #    target: /openmetric/conf/api.yaml
    volumes:
      - /opt/docker/GraphHouse/api/config/carbonapi.yml:/etc/carbonapi.yml
    depends_on:
      - graphite
    networks:
      graphhouse-net:
        aliases:
         - carbonapi
  
  carbon:
    image: lomik/carbon-clickhouse:v0.11.1
    deploy:
      mode: replicated
      replicas: 1
    #configs: 
    #  - source: GraphHouse_carbon-carbon-clickhouse.conf-20190530.1000
    #    target: /etc/carbon-clickhouse/carbon-clickhouse.conf
    volumes:
      - /opt/docker/GraphHouse/carbon/data:/data/carbon-clickhouse
      - /opt/docker/GraphHouse/carbon/config/carbon-clickhouse.conf:/etc/carbon-clickhouse/carbon-clickhouse.conf
    depends_on:
      - clickhouse
    networks:
      graphhouse-net:
        aliases:
         - carbon-clickhouse

  clickhouse:
    image: yandex/clickhouse-server:21.3-alpine
    deploy:
      mode: replicated
      replicas: 1
    #configs:
    #  - source: GraphHouse_clickhouse-rollup.xml-20190530.1049
    #    target: /etc/clickhouse-server/config.d/rollup.xml
    #  - source: GraphHouse_clickhouse-init.sql-20190530.1000
    #    target: /docker-entrypoint-initdb.d/init.sql
    #ports:
    #  - 8123:8123
    volumes:
      - /opt/docker/GraphHouse/clickhouse/data:/var/lib/clickhouse/data
      - /opt/docker/GraphHouse/clickhouse/metadata:/var/lib/clickhouse/metadata
      - /opt/docker/GraphHouse/clickhouse/config/rollup.xml:/etc/clickhouse-server/config.d/rollup.xml
      - /opt/docker/GraphHouse/clickhouse/config/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - graphhouse-net

  graphite:
    image: lomik/graphite-clickhouse:v0.12.0
    deploy:
      mode: replicated
      replicas: 1
    #configs: 
    #  - source: GraphHouse_graphite-graphite-clickhouse.conf-20190530.1000
    #    target: /etc/graphite-clickhouse/graphite-clickhouse.conf
    volumes:
      - /opt/docker/GraphHouse/graphite/config/graphite-clickhouse.conf:/etc/graphite-clickhouse/graphite-clickhouse.conf
    depends_on:
      - clickhouse
    networks:
      graphhouse-net:
        aliases:
         - graphite-clickhouse

  relay:
    image: sscvssu/carbon-c-relay:v3.7.2
    deploy:
      mode: replicated
      replicas: 1
    command: carbon-c-relay -f /etc/carbon-c-relay/carbon-c-relay.conf -c -_:#@%$$|
    #configs:
    #  - source: GraphHouse_relay_relay.conf-20190606.0803
    #    target: /openmetric/conf/relay.conf
    volumes:
      - /opt/docker/GraphHouse/relay/config/carbon-c-relay.conf:/etc/carbon-c-relay/carbon-c-relay.conf
    ports:
      - "2003:2003"
    depends_on:
      - carbon
    networks:
      graphhouse-net:
        aliases:
          - carbon-c-relay    
      
#configs:
#  GraphHouse_clickhouse-rollup.xml-20190530.1049:
#    external: true
#  GraphHouse_clickhouse-init.sql-20190530.1000:
#    external: true
#  GraphHouse_carbon-carbon-clickhouse.conf-20190530.1000:
#    external: true
#  GraphHouse_graphite-graphite-clickhouse.conf-20190530.1000:
#    external: true
#  GraphHouse_api-api.yaml-20190530.1000: 
#    external: true
#  GraphHouse_relay_relay.conf-20190606.0803:
#    external: true
  
networks:
  graphhouse-net:
    external: true