version: "3.6"

services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:7.0.1
    deploy:
      mode: replicated
      replicas: 0
    environment:
      - setup.kibana.host=kibana:5601
    configs:
      - source: Heartbeat_heartbeat-vmware.yml_20190510.1542
        target: /usr/share/heartbeat/heartbeat.yml
    networks:
      - elastic-net
      
networks:
  elastic-net:
    external: true
    
configs:
  Heartbeat_heartbeat-vmware.yml_20190510.1542:
    external: true