version: "3.6"

services:
  filter:
    image: moira/filter
    depends_on:
      - redis
    configs:
#      - source: Moira_filter-schemas.conf-20190530.1450
#        target: /etc/moira/storage-schemas.conf
      - source: Moira_filter-filter.yml-20190530.1438
        target: /etc/moira/filter.yml
    networks:
      - default
      - graphhouse-net
      - redis-net
    deploy:
      mode: replicated
      replicas: 1

  checker:
    image: moira/checker
    depends_on:
      - filter
    networks:
      - default
      - graphhouse-net
      - redis-net
    configs:
      - source: Moira_checker-checker.yml-20190530.1454
        target: /etc/moira/checker.yml
    deploy:
      mode: replicated
      replicas: 1

  notifier:
    image: moira/notifier
    depends_on:
      - checker
    networks:
      - default
      - graphhouse-net
      - redis-net
    deploy:
      mode: replicated
      replicas: 1
    configs:
      - source: Moira_notifier-notifier.yml-20190531.1153
        target: /etc/moira/notifier.yml  
      

  api:
    image: moira/api
    depends_on:
      - checker
    networks:
      - default
#      - traefik-net
      - graphhouse-net
      - redis-net
    configs:
      - source: Moira_api-api.yml-20190530.1503
        target: /etc/moira/api.yml
    deploy:
      mode: replicated
      replicas: 1
#      labels:
#        - "traefik.enable=true"
#        - "traefik.frontend.rule=PathPrefix:/moira/api/"
#        - "traefik.port=8081"

  web:
    image: moira/web2
#    environment:
#      - MOIRA_API_URI=${HOSTIPFQDN}/moira/api
    networks:
      - default
#      - traefik-net
      - graphhouse-net
    deploy:
      mode: replicated
      replicas: 1
#      labels:
#        - "traefik.enable=true"
#        - "traefik.frontend.rule=PathPrefix:/moira/"
#        - "traefik.port=80"

  balancer:
    image: nginx:alpine
    ports:
      - 8083:8083
    depends_on:
      - web
      - api
#    networks:
#      - default
#      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
#      labels:
#        - "traefik.enable=true"
#        - "traefik.frontend.rule=PathPrefix:/moira/"
#        - "traefik.port=8083"
    configs:
      - source: Moira_balancer_nginx.conf-20190531.0727
        target: /etc/nginx/conf.d/moira.conf
        
configs:
  Moira_filter-schemas.conf-20190530.1450:
    external: true
  Moira_filter-filter.yml-20190530.1438:
    external: true
  Moira_checker-checker.yml-20190530.1454:
    external: true
  Moira_api-api.yml-20190530.1503:
    external: true
  Moira_balancer_nginx.conf-20190531.0727:
    external: true
  Moira_notifier-notifier.yml-20190531.1153:
    external: true
    
networks:
  traefik-net:
    external: true
  graphhouse-net:
    external: true
  redis-net:
    external: true