version: "3.6"

services:
  redis:
    image: redis:5.0.5-alpine
    command: redis-server --appendonly yes
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /opt/docker/stack.redis/service.redis/data:/data
    networks:
      default:
      redis-net:
        aliases:
         - redis

  commander:
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    networks:
      - default
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefixStrip:/redis/"
        - "traefik.port=8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      
networks:
  redis-net:
    external: true
  traefik-net:
    external: true