version: "3.3"

services:
  cluster:
    image: telegraf:1.10.0-alpine
    command: telegraf
    environment:
      - VCENTERS=$VCENTERS
      - VCUSERNAME=$VCUSERNAME
      - VCPASSWORD=$VCPASSWORD
    volumes:
      - /opt/docker/Telegraf/cluster/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - graphhouse-net
    deploy:
      mode: replicated
      replicas: 0


  datacenter:
    image: telegraf:1.10.0-alpine
    command: telegraf
    environment:
      - VCENTERS=$VCENTERS
      - VCUSERNAME=$VCUSERNAME
      - VCPASSWORD=$VCPASSWORD
    volumes:
      - /opt/docker/Telegraf/datacenter/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - graphhouse-net
    deploy:
      mode: replicated
      replicas: 0


  datastore:
    image: telegraf:1.10.0-alpine
    command: telegraf
    environment:
      - VCENTERS=$VCENTERS
      - VCUSERNAME=$VCUSERNAME
      - VCPASSWORD=$VCPASSWORD
    volumes:
      - /opt/docker/Telegraf/datastore/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - graphhouse-net
    deploy:
      mode: replicated
      replicas: 1

      
  host:
    image: telegraf:1.10.0-alpine
    command: telegraf
    environment:
      - VCENTERS=$VCENTERS
      - VCUSERNAME=$VCUSERNAME
      - VCPASSWORD=$VCPASSWORD
    volumes:
      - /opt/docker/Telegraf/host/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - graphhouse-net
    deploy:
      mode: replicated
      replicas: 1


  vm:
    image: telegraf:1.10.0-alpine
    command: telegraf
    environment:
      - VCENTERS=$VCENTERS
      - VCUSERNAME=$VCUSERNAME
      - VCPASSWORD=$VCPASSWORD
    volumes:
      - /opt/docker/Telegraf/vm/telegraf.conf:/etc/telegraf/telegraf.conf
    networks:
      - graphhouse-net
    deploy:
      mode: replicated
      replicas: 1

networks:
  graphhouse-net:
    external: true
