listen: "0.0.0.0:8080"
# Controls headers that would be passed to the backend
headersToPass:
  - "X-Dashboard-Id"
  - "X-Grafana-Org-Id"
  - "X-Panel-Id"
concurrency: 200
cache:
  type: "mem"
  size_mb: 0
  defaultTimeoutSec: 60
cpus: 0
tz: ""
#functionsConfig:
#  graphiteWeb: /etc/graphiteWeb.yml
sendGlobsAsIs: false
maxBatchSize: 100
graphite:
  host: relay:2003
  interval: "60s"
  prefix: "graphite.api"
  pattern: "{prefix}.{fqdn}"
idleConnections: 10
pidFile: ""
upstreams:
  buckets: 10
  timeouts:
    global: "10s"
    afterStarted: "2s"
    connect: "200ms"
  cconcurrencyLimitPerServer: 1000
  keepAliveInterval: "30s"
  maxIdleConnsPerHost: 100
  backendsv2:
    backends:
      -
        groupName: "clickhouse-cluster-2"
        protocol: "carbonapi_v2_pb"
        lbMethod: "rr"
        maxTries: 3
        maxBatchSize: 0
        keepAliveInterval: "30s"
        concurrencyLimit: 1000
        maxIdleConnsPerHost: 1000
        timeouts:
            find: "10s"
            render: "50s"
            connect: "200ms"
        servers:
            - "http://graphite-clickhouse:9090"

#graphTemplates: /etc/graphTemplates.yml
expireDelaySec: 10
logger:
  - logger: ""
    file: "stdout"
    level: "info"
    encoding: "console"
    encodingTime: "iso8601"
    encodingDuration: "seconds"
