{
 "title": "Graphite",
 "tags": [
  "graphite",
  "carbon"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "relays", "query": "carbon.relays.*" },
   { "name": "carbons", "query": "carbon.carbon.*" },
   { "name": "apis", "query": "carbon.api.*" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Relay - Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "target": "sumSeries(carbon.relays.043e8543ebdc.metricsReceived)"
    }
   ]
  },
  {
   "title": "Relay - Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(carbon.relays.$relays.destinations.carbon:2003.queued)"
    }
   ]
  },
  {
   "title": "Go-Carbon - Commits",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(carbon.carbon.$carbons.persister.committedPoints)"
    }
   ]
  },
  {
   "title": "Go-Carbon - Updates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(carbon.carbon.$carbons.persister.updateOperations)"
    }
   ]
  },
  {
   "title": "Go-Carbon - Creates",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(carbon.carbon.$carbons.persister.created)"
    }
   ]
  },
  {
   "title": "Go-Carbon - Received",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "sumSeries(carbon.carbon.$carbons.tcp.metricsReceived)"
    }
   ]
  },
  { "title": "Relay", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Relay - Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.relays.$relays.metricsReceived), 'Received')"
    },
    {
     "target": "alias(sumSeries(carbon.relays.$relays.metricsSent), 'Sent')"
    }
   ]
  },
  {
   "title": "Relay - Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.relays.$relays.metricsQueued), 'Queued')"
    },
    {
     "target": "alias(sumSeries(carbon.relays.$relays.metricsDropped), 'Dropped')"
    },
    {
     "target": "alias(sumSeries(carbon.relays.$relays.metricsBlackholed), 'Blackholed')"
    }
   ]
  },
  { "title": "Go-Carbon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Go-Carbon - Persister",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.persister.updateOperations), 'Updates')"
    },
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.persister.committedPoints), 'Committed')"
    },
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.persister.created), 'Creates')"
    },
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.persister.pointsPerUpdate), 'Points Per Update')"
    }
   ]
  },
  {
   "title": "Go-Carbon - Metrics Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.tcp.metricsReceived), 'TCP')"
    },
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.udp.metricsReceived), 'UDP')"
    }
   ]
  },
  {
   "title": "Go-Carbon - Cache Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.cache.size), 'Size')"
    }
   ]
  },
  {
   "title": "Go-Carbon - CarbonServer - Disk",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(sumSeries(carbon.carbon.$carbons.carbonserver.disk_requests))"
    }
   ]
  },
  {
   "title": "Go-Carbon - CarbonServer - Find Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.carbonserver.find_cache_hit), 'Hit')"
    },
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.carbonserver.find_cache_miss), 'Miss')"
    }
   ]
  },
  {
   "title": "Go-Carbon - CarbonServer - Query Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.carbonserver.query_cache_hit), 'Hit')"
    },
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.carbonserver.find_cache_miss), 'Miss')"
    }
   ]
  },
  {
   "title": "Go-Carbon - CarbonServer - Query Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.carbon.$carbons.carbonserver.query_cache_hit), 'Hit')"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "API - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(carbon.api.$apis.render_requests), 'Render')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.find_requests)), 'Find')"
    }
   ]
  },
  {
   "title": "API - Find Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.find_cache_hits)), 'Hits')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.find_cache_misses)), 'Misses')"
    }
   ]
  },
  {
   "title": "API - Request Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.request_cache_hits)), 'Hits')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.request_cache_misses)), 'Misses')"
    }
   ]
  },
  {
   "title": "API - Cache overhead",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 28 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.find_cache_overhead_ns)), 'Find')"
    },
    {
     "target": "alias(sumSeries(nonNegativeDerivative(carbon.api.$apis.request_cache_overhead_ns)), 'Request')"
    }
   ]
  }
 ]
}