{
 "title": "Telegraf",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Agent", "query": "telegraf.*" },
   { "name": "Plugin", "query": "telegraf.$Agent.plugins.*" }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(perSecond(keepLastValue(telegraf.$Agent.metrics_gathered, 120))), 'Gathered')"
    },
    {
     "target": "alias(sumSeries(perSecond(keepLastValue(telegraf.$Agent.metrics_written, 120))), 'Written')"
    }
   ]
  },
  {
   "title": "Metric Write Ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(asPercent(sumSeries(perSecond(keepLastValue(telegraf.$Agent.metrics_written, 120))), #A), 'Written')",
     "targetFull": "alias(asPercent(sumSeries(perSecond(keepLastValue(telegraf.$Agent.metrics_written, 120))), alias(sumSeries(perSecond(keepLastValue(telegraf.$Agent.metrics_gathered, 120))), 'Gathered')), 'Written')"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(perSecond(keepLastValue(telegraf.$Agent.gather_errors, 60))), 'Gather Errors')"
    },
    {
     "target": "alias(sumSeries(perSecond(keepLastValue(telegraf.$Agent.metrics_dropped, 60))), 'Metrics Dropped')"
    }
   ]
  },
  {
   "title": "Plugin Gather Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(telegraf.$Agent.plugins.*.gather_time_ns, 60)), 'Average')"
    },
    {
     "target": "alias(maxSeries(keepLastValue(telegraf.$Agent.plugins.*.gather_time_ns, 60)), 'Maximum')"
    }
   ]
  },
  {
   "title": "Slowest Plugins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "aliasByNode(limit(averageSeriesWithWildcards(keepLastValue(telegraf.$Agent.plugins.*.gather_time_ns, 60), 1), 5), 2)"
    }
   ]
  },
  {
   "title": "Graphite Write Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(telegraf.$Agent.plugins.graphite.write_time_ns, 60)), 'Average')"
    },
    {
     "target": "alias(maxSeries(keepLastValue(telegraf.$Agent.plugins.graphite.write_time_ns, 60)), 'Maximum')"
    }
   ]
  },
  {
   "title": "Graphite Buffer Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(telegraf.$Agent.plugins.graphite.buffer_size, 60)), 'Average')"
    },
    {
     "target": "alias(maxSeries(keepLastValue(telegraf.$Agent.plugins.graphite.buffer_size, 60)), 'Maximum')"
    }
   ]
  },
  {
   "title": "$Plugin",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "repeat": "Plugin",
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "target": "alias(averageSeries(keepLastValue(telegraf.$Agent.plugins.$Plugin.gather_time_ns, 60)), 'Average')"
    },
    {
     "target": "alias(maxSeries(keepLastValue(telegraf.$Agent.plugins.$Plugin.gather_time_ns, 60)), 'Maximum')"
    }
   ]
  },
  {
   "title": "Plugin Gather times",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "target": "aliasByNode(scale(keepLastValue(averageSeriesWithWildcards(telegraf.$Agent.plugins.$Plugin.gather_time_ns, 1), 60), 0.000001), 2)"
    }
   ]
  }
 ]
}